In [22]:
import pandas as pd
import numpy as np

train1 = pd.read_csv('data\mnist_train_0_1.csv', header= 0)
train1.shape

(12664, 785)

In [19]:
data = np.array(train1)

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [29]:

workingData = data.T
workingData

array([[1, 1, 1, ..., 1, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [30]:
m, n = workingData.shape

yWorking = workingData[0]
xWorking = workingData[1: n]

yWorking

array([1, 1, 1, ..., 1, 0, 1], dtype=int64)